#!/usr/bin/env python3
"""Gera ~1000 flashcards de vocabulário italiano essencial (módulo 'essenciais'),
incluindo adjetivos e substantivos no singular E no plural.

Para garantir correção, TODAS as formas (inclusive plurais irregulares dos dois
idiomas) são fornecidas explicitamente nas tabelas abaixo. Saída:
lib/data/cards_essenciais.dart. Não edite o .dart à mão — rode este script.
"""

# Substantivos: (it_sing, it_plur, pt_sing, pt_plur, nivel) -> 2 cartões
NOUN_PAIRS = [
    ("uomo", "uomini", "homem", "homens", "a1"),
    ("donna", "donne", "mulher", "mulheres", "a1"),
    ("ragazzo", "ragazzi", "rapaz", "rapazes", "a1"),
    ("ragazza", "ragazze", "moça", "moças", "a1"),
    ("bambino", "bambini", "menino", "meninos", "a1"),
    ("bambina", "bambine", "menina", "meninas", "a1"),
    ("persona", "persone", "pessoa", "pessoas", "a1"),
    ("amico", "amici", "amigo", "amigos", "a1"),
    ("amica", "amiche", "amiga", "amigas", "a1"),
    ("gatto", "gatti", "gato", "gatos", "a1"),
    ("cane", "cani", "cachorro", "cachorros", "a1"),
    ("cavallo", "cavalli", "cavalo", "cavalos", "a2"),
    ("uccello", "uccelli", "pássaro", "pássaros", "a2"),
    ("pesce", "pesci", "peixe", "peixes", "a1"),
    ("fiore", "fiori", "flor", "flores", "a1"),
    ("albero", "alberi", "árvore", "árvores", "a2"),
    ("foglia", "foglie", "folha", "folhas", "a2"),
    ("frutto", "frutti", "fruto", "frutos", "a2"),
    ("mela", "mele", "maçã", "maçãs", "a1"),
    ("pera", "pere", "pera", "peras", "a2"),
    ("uovo", "uova", "ovo", "ovos", "a1"),
    ("libro", "libri", "livro", "livros", "a1"),
    ("penna", "penne", "caneta", "canetas", "a1"),
    ("tavolo", "tavoli", "mesa", "mesas", "a1"),
    ("sedia", "sedie", "cadeira", "cadeiras", "a1"),
    ("porta", "porte", "porta", "portas", "a1"),
    ("finestra", "finestre", "janela", "janelas", "a1"),
    ("casa", "case", "casa", "casas", "a1"),
    ("chiave", "chiavi", "chave", "chaves", "a1"),
    ("strada", "strade", "rua", "ruas", "a1"),
    ("ponte", "ponti", "ponte", "pontes", "a2"),
    ("città", "città", "cidade", "cidades", "a1"),
    ("paese", "paesi", "país", "países", "a2"),
    ("via", "vie", "via", "vias", "a2"),
    ("piazza", "piazze", "praça", "praças", "a2"),
    ("chiesa", "chiese", "igreja", "igrejas", "a2"),
    ("scuola", "scuole", "escola", "escolas", "a1"),
    ("nave", "navi", "navio", "navios", "a2"),
    ("macchina", "macchine", "carro", "carros", "a1"),
    ("treno", "treni", "trem", "trens", "a2"),
    ("strumento", "strumenti", "instrumento", "instrumentos", "b1"),
    ("animale", "animali", "animal", "animais", "a1"),
    ("giornale", "giornali", "jornal", "jornais", "a2"),
    ("ospedale", "ospedali", "hospital", "hospitais", "a2"),
    ("capello", "capelli", "cabelo", "cabelos", "a2"),
    ("occhio", "occhi", "olho", "olhos", "a1"),
    ("mano", "mani", "mão", "mãos", "a1"),
    ("piede", "piedi", "pé", "pés", "a1"),
    ("dito", "dita", "dedo", "dedos", "a2"),
    ("dente", "denti", "dente", "dentes", "a2"),
    ("braccio", "braccia", "braço", "braços", "a2"),
    ("gamba", "gambe", "perna", "pernas", "a2"),
    ("cuore", "cuori", "coração", "corações", "a2"),
    ("faccia", "facce", "cara", "caras", "a2"),
    ("testa", "teste", "cabeça", "cabeças", "a2"),
    ("figlio", "figli", "filho", "filhos", "a1"),
    ("figlia", "figlie", "filha", "filhas", "a1"),
    ("fratello", "fratelli", "irmão", "irmãos", "a1"),
    ("sorella", "sorelle", "irmã", "irmãs", "a1"),
    ("padre", "padri", "pai", "pais", "a1"),
    ("madre", "madri", "mãe", "mães", "a1"),
    ("medico", "medici", "médico", "médicos", "a2"),
    ("parco", "parchi", "parque", "parques", "a2"),
    ("gioco", "giochi", "jogo", "jogos", "a1"),
    ("fuoco", "fuochi", "fogo", "fogos", "a2"),
    ("lago", "laghi", "lago", "lagos", "a2"),
    ("luogo", "luoghi", "lugar", "lugares", "b1"),
    ("albergo", "alberghi", "hotel", "hotéis", "a2"),
    ("banca", "banche", "banco", "bancos", "a2"),
    ("barca", "barche", "barco", "barcos", "a2"),
    ("spiaggia", "spiagge", "praia", "praias", "b1"),
    ("pioggia", "piogge", "chuva", "chuvas", "b1"),
    ("problema", "problemi", "problema", "problemas", "a2"),
    ("tema", "temi", "tema", "temas", "b1"),
    ("programma", "programmi", "programa", "programas", "b1"),
    ("sistema", "sistemi", "sistema", "sistemas", "b1"),
    ("parola", "parole", "palavra", "palavras", "a1"),
    ("frase", "frasi", "frase", "frases", "a2"),
    ("lingua", "lingue", "língua", "línguas", "a2"),
    ("lettera", "lettere", "carta", "cartas", "a2"),
    ("pagina", "pagine", "página", "páginas", "a2"),
    ("storia", "storie", "história", "histórias", "a2"),
    ("idea", "idee", "ideia", "ideias", "a2"),
    ("colore", "colori", "cor", "cores", "a1"),
    ("numero", "numeri", "número", "números", "a1"),
    ("nome", "nomi", "nome", "nomes", "a1"),
    ("voce", "voci", "voz", "vozes", "a2"),
    ("luce", "luci", "luz", "luzes", "a2"),
    ("notte", "notti", "noite", "noites", "a1"),
    ("mese", "mesi", "mês", "meses", "a1"),
    ("re", "re", "rei", "reis", "b1"),
    ("legge", "leggi", "lei", "leis", "b2"),
    ("stazione", "stazioni", "estação", "estações", "a2"),
    ("lezione", "lezioni", "lição", "lições", "a2"),
    ("canzone", "canzoni", "canção", "canções", "a2"),
    ("opinione", "opinioni", "opinião", "opiniões", "b1"),
    ("ragione", "ragioni", "razão", "razões", "b1"),
    ("regione", "regioni", "região", "regiões", "b1"),
    ("viaggio", "viaggi", "viagem", "viagens", "a2"),
    ("esempio", "esempi", "exemplo", "exemplos", "b1"),
    ("giorno", "giorni", "dia", "dias", "a1"),
    ("anno", "anni", "ano", "anos", "a1"),
    ("mano", "mani", "mão", "mãos", "a1"),
    ("ora", "ore", "hora", "horas", "a1"),
    ("scatola", "scatole", "caixa", "caixas", "a2"),
    ("borsa", "borse", "bolsa", "bolsas", "a2"),
    ("camicia", "camicie", "camisa", "camisas", "a2"),
    ("scarpa", "scarpe", "sapato", "sapatos", "a2"),
    ("cappello", "cappelli", "chapéu", "chapéus", "a2"),
    ("vestito", "vestiti", "vestido", "vestidos", "a2"),
    ("finestra", "finestre", "janela", "janelas", "a1"),
]

# Adjetivos: (it_msing, it_plur, pt_sing, pt_plur, nivel)
ADJ_PAIRS = [
    ("buono", "buoni", "bom", "bons", "a1"),
    ("cattivo", "cattivi", "ruim", "ruins", "a1"),
    ("bello", "belli", "bonito", "bonitos", "a1"),
    ("brutto", "brutti", "feio", "feios", "a1"),
    ("nuovo", "nuovi", "novo", "novos", "a1"),
    ("vecchio", "vecchi", "velho", "velhos", "a1"),
    ("giovane", "giovani", "jovem", "jovens", "a1"),
    ("grande", "grandi", "grande", "grandes", "a1"),
    ("piccolo", "piccoli", "pequeno", "pequenos", "a1"),
    ("lungo", "lunghi", "longo", "longos", "a2"),
    ("corto", "corti", "curto", "curtos", "a2"),
    ("alto", "alti", "alto", "altos", "a1"),
    ("basso", "bassi", "baixo", "baixos", "a1"),
    ("largo", "larghi", "largo", "largos", "a2"),
    ("stretto", "stretti", "estreito", "estreitos", "b1"),
    ("forte", "forti", "forte", "fortes", "a2"),
    ("debole", "deboli", "fraco", "fracos", "a2"),
    ("veloce", "veloci", "rápido", "rápidos", "a2"),
    ("lento", "lenti", "lento", "lentos", "a2"),
    ("caldo", "caldi", "quente", "quentes", "a1"),
    ("freddo", "freddi", "frio", "frios", "a1"),
    ("facile", "facili", "fácil", "fáceis", "a1"),
    ("difficile", "difficili", "difícil", "difíceis", "a1"),
    ("ricco", "ricchi", "rico", "ricos", "a2"),
    ("povero", "poveri", "pobre", "pobres", "a2"),
    ("pulito", "puliti", "limpo", "limpos", "a2"),
    ("sporco", "sporchi", "sujo", "sujos", "a2"),
    ("pieno", "pieni", "cheio", "cheios", "a2"),
    ("vuoto", "vuoti", "vazio", "vazios", "a2"),
    ("aperto", "aperti", "aberto", "abertos", "a2"),
    ("chiuso", "chiusi", "fechado", "fechados", "a2"),
    ("felice", "felici", "feliz", "felizes", "a1"),
    ("triste", "tristi", "triste", "tristes", "a2"),
    ("stanco", "stanchi", "cansado", "cansados", "a2"),
    ("malato", "malati", "doente", "doentes", "b1"),
    ("sano", "sani", "saudável", "saudáveis", "b1"),
    ("dolce", "dolci", "doce", "doces", "a2"),
    ("amaro", "amari", "amargo", "amargos", "b1"),
    ("salato", "salati", "salgado", "salgados", "b1"),
    ("duro", "duri", "duro", "duros", "a2"),
    ("morbido", "morbidi", "macio", "macios", "b2"),
    ("pesante", "pesanti", "pesado", "pesados", "b2"),
    ("leggero", "leggeri", "leve", "leves", "b2"),
    ("scuro", "scuri", "escuro", "escuros", "a2"),
    ("chiaro", "chiari", "claro", "claros", "a2"),
    ("profondo", "profondi", "profundo", "profundos", "b2"),
    ("largo", "larghi", "largo", "largos", "a2"),
    ("importante", "importanti", "importante", "importantes", "b1"),
    ("possibile", "possibili", "possível", "possíveis", "b2"),
    ("necessario", "necessari", "necessário", "necessários", "b2"),
    ("vero", "veri", "verdadeiro", "verdadeiros", "a2"),
    ("falso", "falsi", "falso", "falsos", "a2"),
    ("giusto", "giusti", "certo", "certos", "a2"),
    ("sbagliato", "sbagliati", "errado", "errados", "a2"),
    ("simile", "simili", "semelhante", "semelhantes", "b2"),
    ("diverso", "diversi", "diferente", "diferentes", "a2"),
    ("uguale", "uguali", "igual", "iguais", "a2"),
    ("strano", "strani", "estranho", "estranhos", "b1"),
    ("normale", "normali", "normal", "normais", "a2"),
    ("famoso", "famosi", "famoso", "famosos", "b1"),
    ("sconosciuto", "sconosciuti", "desconhecido", "desconhecidos", "b2"),
    ("libero", "liberi", "livre", "livres", "a2"),
    ("occupato", "occupati", "ocupado", "ocupados", "a2"),
    ("sicuro", "sicuri", "seguro", "seguros", "b1"),
    ("pericoloso", "pericolosi", "perigoso", "perigosos", "b2"),
    ("gentile", "gentili", "gentil", "gentis", "a2"),
    ("simpatico", "simpatici", "simpático", "simpáticos", "a2"),
    ("intelligente", "intelligenti", "inteligente", "inteligentes", "a2"),
    ("stupido", "stupidi", "burro", "burros", "b1"),
    ("bravo", "bravi", "bom", "bons", "a2"),
    ("cattivo", "cattivi", "mau", "maus", "a1"),
    ("educato", "educati", "educado", "educados", "b1"),
    ("maleducato", "maleducati", "mal-educado", "mal-educados", "b2"),
    ("tranquillo", "tranquilli", "tranquilo", "tranquilos", "a2"),
    ("nervoso", "nervosi", "nervoso", "nervosos", "a2"),
    ("contento", "contenti", "contente", "contentes", "a2"),
    ("arrabbiato", "arrabbiati", "bravo", "bravos", "a2"),
    ("stesso", "stessi", "mesmo", "mesmos", "a2"),
    ("intero", "interi", "inteiro", "inteiros", "b1"),
    ("vario", "vari", "vário", "vários", "b1"),
    ("certo", "certi", "certo", "certos", "b1"),
    ("solito", "soliti", "habitual", "habituais", "b1"),
    ("raro", "rari", "raro", "raros", "b1"),
    ("comune", "comuni", "comum", "comuns", "b1"),
    ("speciale", "speciali", "especial", "especiais", "b1"),
    ("generale", "generali", "geral", "gerais", "b1"),
    ("principale", "principali", "principal", "principais", "b1"),
    ("nazionale", "nazionali", "nacional", "nacionais", "b2"),
    ("naturale", "naturali", "natural", "naturais", "b1"),
    ("sociale", "sociali", "social", "sociais", "b2"),
    ("personale", "personali", "pessoal", "pessoais", "b2"),
]

# Palavras avulsas: (it, pt, nivel) ou (it, pt, nivel, [alternativas_pt])
SINGLES = [
    # --- Verbos (infinitivo) ---
    ("amare", "amar", "a2"),
    ("odiare", "odiar", "b1"),
    ("baciare", "beijar", "b1"),
    ("abbracciare", "abraçar", "b1"),
    ("ridere", "rir", "a2"),
    ("piangere", "chorar", "a2"),
    ("sorridere", "sorrir", "b1"),
    ("gridare", "gritar", "b1"),
    ("saltare", "pular", "a2"),
    ("volare", "voar", "a2"),
    ("cadere", "cair", "a2"),
    ("salire", "subir", "a2"),
    ("scendere", "descer", "a2"),
    ("uscire", "sair", "a1"),
    ("girare", "girar", "b1"),
    ("muovere", "mover", "b1"),
    ("tirare", "puxar", "b1"),
    ("spingere", "empurrar", "b1"),
    ("lanciare", "lançar", "b1"),
    ("rompere", "quebrar", "a2"),
    ("tagliare", "cortar", "a2"),
    ("dipingere", "pintar", "b1"),
    ("ballare", "dançar", "a1"),
    ("suonare", "tocar", "a2"),
    ("asciugare", "secar", "b1"),
    ("accendere", "acender", "a2"),
    ("spegnere", "apagar", "a2", ["desligar"]),
    ("riempire", "encher", "b1"),
    ("riparare", "consertar", "b1", ["reparar"]),
    ("regalare", "presentear", "b1", ["dar de presente"]),
    ("mandare", "enviar", "a2", ["mandar"]),
    ("ringraziare", "agradecer", "a2"),
    ("viaggiare", "viajar", "a2"),
    ("guidare", "dirigir", "a2", ["guiar", "conduzir"]),
    ("sperare", "esperar", "a2", ["ter esperança"]),
    ("pregare", "rezar", "b1"),
    ("dubitare", "duvidar", "b2"),
    ("scoprire", "descobrir", "b1"),
    ("nascondere", "esconder", "b1"),
    ("cercare", "procurar", "a1", ["buscar"]),
    ("vincere", "vencer", "a2", ["ganhar"]),
    ("allenare", "treinar", "b1"),
    ("riposare", "descansar", "a2"),
    ("svegliare", "acordar", "a2", ["despertar"]),
    ("piacere", "agradar", "a2"),
    ("mancare", "faltar", "a2"),
    ("bastare", "bastar", "a2", ["ser suficiente"]),
    ("accadere", "acontecer", "b2", ["ocorrer"]),
    ("durare", "durar", "b1"),
    ("continuare", "continuar", "a2"),
    ("smettere", "parar", "b1", ["parar de"]),
    ("ordinare", "pedir", "a2", ["ordenar"]),
    ("prenotare", "reservar", "a2"),
    ("affittare", "alugar", "b1"),
    ("restituire", "devolver", "b1"),
    ("costare", "custar", "a1"),
    ("risparmiare", "poupar", "b1", ["economizar"]),
    ("guadagnare", "ganhar", "b1"),
    ("firmare", "assinar", "b1"),
    ("stampare", "imprimir", "b1"),
    ("scaricare", "baixar", "b1", ["descarregar"]),
    ("salvare", "salvar", "b1"),
    ("condividere", "compartilhar", "b2"),
    ("collegare", "conectar", "b2", ["ligar"]),
    # --- Substantivos (incontáveis / abstratos / diversos) ---
    ("vita", "vida", "a1"),
    ("morte", "morte", "a2"),
    ("amore", "amor", "a1"),
    ("odio", "ódio", "b1"),
    ("mondo", "mundo", "a1"),
    ("gente", "gente", "a1"),
    ("cosa", "coisa", "a1"),
    ("modo", "modo", "a2", ["jeito", "maneira"]),
    ("posto", "lugar", "a1"),
    ("fine", "fim", "a2"),
    ("inizio", "início", "a2", ["começo"]),
    ("festa", "festa", "a1"),
    ("regalo", "presente", "a2"),
    ("sogno", "sonho", "a2"),
    ("mente", "mente", "b1"),
    ("pensiero", "pensamento", "b1"),
    ("fame", "fome", "a1"),
    ("sete", "sede", "a1"),
    ("sonno", "sono", "a2"),
    ("voglia", "vontade", "a2"),
    ("bisogno", "necessidade", "b1"),
    ("coraggio", "coragem", "b1"),
    ("forza", "força", "a2"),
    ("energia", "energia", "b1"),
    ("salute", "saúde", "a2"),
    ("sorriso", "sorriso", "a2"),
    ("lacrima", "lágrima", "b1"),
    ("bacio", "beijo", "a2"),
    ("abbraccio", "abraço", "a2"),
    ("silenzio", "silêncio", "a2"),
    ("rumore", "barulho", "a2", ["ruído"]),
    ("suono", "som", "a2"),
    ("musica", "música", "a1"),
    ("immagine", "imagem", "b1"),
    ("disegno", "desenho", "a2"),
    ("rivista", "revista", "a2"),
    ("notizia", "notícia", "a2"),
    ("racconto", "conto", "b1"),
    ("romanzo", "romance", "b1"),
    ("poesia", "poesia", "b1"),
    ("articolo", "artigo", "b1"),
    ("posta", "correio", "a2"),
    ("pacco", "pacote", "b1"),
    ("oggetto", "objeto", "b1"),
    ("motore", "motor", "b1"),
    ("benzina", "gasolina", "b1"),
    ("semaforo", "semáforo", "b1"),
    ("fila", "fila", "a2"),
    ("folla", "multidão", "b2"),
    ("rumore", "barulho", "a2"),
    ("verità", "verdade", "b2"),
    ("bugia", "mentira", "b1"),
    ("scherzo", "brincadeira", "b1", ["piada"]),
    ("dubbio", "dúvida", "b1"),
    ("scelta", "escolha", "b2"),
    ("errore", "erro", "a2"),
    ("colpa", "culpa", "b1"),
    ("aiuto", "ajuda", "a2"),
    ("consiglio", "conselho", "b1"),
    ("favore", "favor", "a2"),
    ("permesso", "permissão", "b1"),
    ("ricordo", "lembrança", "b1", ["recordação"]),
    ("abitudine", "hábito", "b2", ["costume"]),
    ("esperienza", "experiência", "b2"),
    ("conoscenza", "conhecimento", "b2"),
    ("capacità", "capacidade", "b2"),
    ("qualità", "qualidade", "b1"),
    ("quantità", "quantidade", "b1"),
    ("velocità", "velocidade", "b1"),
    ("difficoltà", "dificuldade", "b1"),
    ("possibilità", "possibilidade", "b2"),
    ("attività", "atividade", "b1"),
    ("realtà", "realidade", "b2"),
    ("società", "sociedade", "b2"),
    ("libertà", "liberdade", "b2"),
    ("felicità", "felicidade", "b1"),
    # --- Advérbios e expressões de quantidade/tempo/lugar ---
    ("qui", "aqui", "a1"),
    ("qua", "cá", "a2"),
    ("lì", "ali", "a1", ["lá"]),
    ("là", "lá", "a1"),
    ("sopra", "em cima", "a2", ["acima"]),
    ("sotto", "embaixo", "a2", ["abaixo"]),
    ("dentro", "dentro", "a1"),
    ("fuori", "fora", "a1"),
    ("davanti", "na frente", "a2", ["à frente"]),
    ("dietro", "atrás", "a2"),
    ("vicino", "perto", "a1"),
    ("lontano", "longe", "a1"),
    ("dappertutto", "em todo lugar", "b1"),
    ("altrove", "em outro lugar", "b2"),
    ("oggi", "hoje", "a1"),
    ("ieri", "ontem", "a1"),
    ("domani", "amanhã", "a1"),
    ("adesso", "agora", "a1", ["agora mesmo"]),
    ("ora", "agora", "a1"),
    ("dopo", "depois", "a1"),
    ("prima", "antes", "a1"),
    ("poi", "depois", "a1", ["então"]),
    ("ancora", "ainda", "a2"),
    ("già", "já", "a2"),
    ("presto", "cedo", "a2", ["logo"]),
    ("tardi", "tarde", "a2"),
    ("sempre", "sempre", "a1"),
    ("mai", "nunca", "a1", ["jamais"]),
    ("spesso", "frequentemente", "b1", ["muitas vezes"]),
    ("raramente", "raramente", "b1"),
    ("subito", "logo", "a2", ["imediatamente"]),
    ("molto", "muito", "a1"),
    ("poco", "pouco", "a1"),
    ("troppo", "demais", "a2", ["demasiado"]),
    ("abbastanza", "bastante", "b1", ["o suficiente"]),
    ("quasi", "quase", "a2"),
    ("circa", "cerca de", "b1", ["aproximadamente"]),
    ("più", "mais", "a1"),
    ("meno", "menos", "a1"),
    ("tanto", "tanto", "a2"),
    ("così", "assim", "a2"),
    ("bene", "bem", "a1"),
    ("male", "mal", "a1"),
    ("meglio", "melhor", "a2"),
    ("peggio", "pior", "a2"),
    ("forse", "talvez", "a2", ["quem sabe"]),
    ("davvero", "realmente", "b1", ["de verdade"]),
    ("certamente", "certamente", "b1", ["com certeza"]),
    ("veramente", "verdadeiramente", "b1", ["de fato"]),
    ("soprattutto", "sobretudo", "b2", ["principalmente"]),
    ("almeno", "pelo menos", "b1"),
    ("insieme", "juntos", "a2", ["junto"]),
    ("solo", "só", "a1", ["somente", "apenas"]),
    ("soltanto", "apenas", "b1", ["somente"]),
    ("anche", "também", "a1"),
    ("neanche", "nem", "b1", ["tampouco"]),
    ("piuttosto", "em vez", "b2", ["bastante"]),
    # --- Pronomes, interrogativos e conectores ---
    ("chi", "quem", "a1"),
    ("che", "que", "a1", ["o que"]),
    ("cosa", "o que", "a1"),
    ("quale", "qual", "a1"),
    ("quanto", "quanto", "a1"),
    ("come", "como", "a1"),
    ("dove", "onde", "a1"),
    ("quando", "quando", "a1"),
    ("perché", "por que", "a1", ["porque"]),
    ("io", "eu", "a1"),
    ("tu", "você", "a1", ["tu"]),
    ("lui", "ele", "a1"),
    ("lei", "ela", "a1"),
    ("noi", "nós", "a1"),
    ("voi", "vocês", "a1"),
    ("loro", "eles", "a1", ["elas"]),
    ("questo", "este", "a1", ["isto"]),
    ("quello", "aquele", "a1", ["aquilo"]),
    ("ogni", "cada", "a2"),
    ("tutto", "tudo", "a1", ["todo"]),
    ("niente", "nada", "a1"),
    ("nulla", "nada", "b1"),
    ("qualcosa", "algo", "a2", ["alguma coisa"]),
    ("qualcuno", "alguém", "a2"),
    ("nessuno", "ninguém", "a2"),
    ("ognuno", "cada um", "b1"),
    ("alcuni", "alguns", "b1"),
    ("molti", "muitos", "a2"),
    ("pochi", "poucos", "a2"),
    ("entrambi", "ambos", "b2"),
    ("e", "e", "a1"),
    ("o", "ou", "a1"),
    ("ma", "mas", "a1"),
    ("però", "porém", "b1", ["no entanto"]),
    ("quindi", "portanto", "b1", ["então"]),
    ("perciò", "por isso", "b2"),
    ("dunque", "portanto", "b2", ["então"]),
    ("infatti", "de fato", "b2", ["com efeito"]),
    ("cioè", "ou seja", "b1", ["isto é"]),
    ("inoltre", "além disso", "b2"),
    ("mentre", "enquanto", "b1"),
    ("appena", "assim que", "b1", ["mal"]),
    ("finché", "até que", "b2", ["enquanto"]),
    ("benché", "embora", "c1", ["ainda que"]),
    ("affinché", "para que", "c1", ["a fim de que"]),
    # --- Comida e diversos extras ---
    ("zucchero", "açúcar", "a2"),
    ("sale", "sal", "a2"),
    ("pepe", "pimenta", "b1"),
    ("aglio", "alho", "b1"),
    ("cipolla", "cebola", "b1"),
    ("patata", "batata", "a2"),
    ("pomodoro", "tomate", "a2"),
    ("insalata", "salada", "a2"),
    ("minestra", "sopa", "a2", ["caldo"]),
    ("dolce", "doce", "a2", ["sobremesa"]),
    ("cioccolato", "chocolate", "a2"),
    ("gelato", "sorvete", "a1"),
    ("bevanda", "bebida", "a2"),
    ("acqua", "água", "a1"),
    ("vino", "vinho", "a1"),
    ("birra", "cerveja", "a1"),
    ("succo", "suco", "a2"),
    ("colazione", "café da manhã", "a2"),
    ("pranzo", "almoço", "a2"),
    ("cena", "jantar", "a2"),
    ("piatto", "prato", "a2"),
    ("bicchiere", "copo", "a2"),
    ("tazza", "xícara", "a2"),
    ("forchetta", "garfo", "a2"),
    ("coltello", "faca", "a2"),
    ("cucchiaio", "colher", "a2"),
    ("tovagliolo", "guardanapo", "b1"),
    ("bottiglia", "garrafa", "a2"),
]

LEVELS = {"a1", "a2", "b1", "b2", "c1"}

# ---------------------------------------------------------------------------
# Bloco EXTRA (para ampliar o total para ~1000+ cartões essenciais).
# ---------------------------------------------------------------------------
EXTRA_NOUN_PAIRS = [
    ("stanza", "stanze", "quarto", "quartos", "a2"),
    ("cucina", "cucine", "cozinha", "cozinhas", "a2"),
    ("bagno", "bagni", "banheiro", "banheiros", "a2"),
    ("letto", "letti", "cama", "camas", "a2"),
    ("muro", "muri", "parede", "paredes", "a2"),
    ("tetto", "tetti", "telhado", "telhados", "a2"),
    ("scala", "scale", "escada", "escadas", "a2"),
    ("giardino", "giardini", "jardim", "jardins", "a2"),
    ("specchio", "specchi", "espelho", "espelhos", "a2"),
    ("lampada", "lampade", "lâmpada", "lâmpadas", "a2"),
    ("torre", "torri", "torre", "torres", "b1"),
    ("castello", "castelli", "castelo", "castelos", "b1"),
    ("palazzo", "palazzi", "prédio", "prédios", "b1"),
    ("edificio", "edifici", "edifício", "edifícios", "b1"),
    ("appartamento", "appartamenti", "apartamento", "apartamentos", "a2"),
    ("quartiere", "quartieri", "bairro", "bairros", "b1"),
    ("isola", "isole", "ilha", "ilhas", "b1"),
    ("montagna", "montagne", "montanha", "montanhas", "b1"),
    ("collina", "colline", "colina", "colinas", "b1"),
    ("valle", "valli", "vale", "vales", "b1"),
    ("fiume", "fiumi", "rio", "rios", "b1"),
    ("mare", "mari", "mar", "mares", "b1"),
    ("stella", "stelle", "estrela", "estrelas", "b1"),
    ("nuvola", "nuvole", "nuvem", "nuvens", "b1"),
    ("onda", "onde", "onda", "ondas", "b1"),
    ("pietra", "pietre", "pedra", "pedras", "b1"),
    ("campo", "campi", "campo", "campos", "b1"),
    ("ufficio", "uffici", "escritório", "escritórios", "a2"),
    ("negozio", "negozi", "loja", "lojas", "a2"),
    ("mercato", "mercati", "mercado", "mercados", "a2"),
    ("museo", "musei", "museu", "museus", "a2"),
    ("teatro", "teatri", "teatro", "teatros", "a2"),
    ("ristorante", "ristoranti", "restaurante", "restaurantes", "a2"),
    ("spettacolo", "spettacoli", "espetáculo", "espetáculos", "b2"),
    ("biglietto", "biglietti", "bilhete", "bilhetes", "a2"),
    ("moneta", "monete", "moeda", "moedas", "b1"),
    ("prezzo", "prezzi", "preço", "preços", "a2"),
    ("premio", "premi", "prêmio", "prêmios", "b1"),
    ("gara", "gare", "competição", "competições", "b1"),
    ("squadra", "squadre", "time", "times", "b1"),
    ("giocatore", "giocatori", "jogador", "jogadores", "b1"),
    ("partita", "partite", "partida", "partidas", "b1"),
    ("palla", "palle", "bola", "bolas", "a2"),
    ("professore", "professori", "professor", "professores", "a1"),
    ("studente", "studenti", "estudante", "estudantes", "a1"),
    ("operaio", "operai", "operário", "operários", "b1"),
    ("cuoco", "cuochi", "cozinheiro", "cozinheiros", "a2"),
    ("soldato", "soldati", "soldado", "soldados", "b1"),
    ("artista", "artisti", "artista", "artistas", "b1"),
    ("scrittore", "scrittori", "escritor", "escritores", "b1"),
    ("attore", "attori", "ator", "atores", "b1"),
    ("pittore", "pittori", "pintor", "pintores", "b1"),
    ("nemico", "nemici", "inimigo", "inimigos", "b1"),
    ("cittadino", "cittadini", "cidadão", "cidadãos", "b2"),
    ("collega", "colleghi", "colega", "colegas", "b1"),
    ("direttore", "direttori", "diretor", "diretores", "b1"),
    ("cliente", "clienti", "cliente", "clientes", "a2"),
    ("coppia", "coppie", "casal", "casais", "b1"),
    ("parente", "parenti", "parente", "parentes", "b1"),
    ("regola", "regole", "regra", "regras", "b1"),
    ("ruota", "ruote", "roda", "rodas", "b1"),
    ("aereo", "aerei", "avião", "aviões", "a2"),
    ("ala", "ali", "asa", "asas", "b2"),
    ("coda", "code", "rabo", "rabos", "b1"),
    ("zampa", "zampe", "pata", "patas", "b2"),
    ("insetto", "insetti", "inseto", "insetos", "b1"),
    ("mosca", "mosche", "mosca", "moscas", "b1"),
    ("formica", "formiche", "formiga", "formigas", "b2"),
    ("ragno", "ragni", "aranha", "aranhas", "b2"),
    ("ramo", "rami", "galho", "galhos", "b2"),
    ("radice", "radici", "raiz", "raízes", "b2"),
    ("seme", "semi", "semente", "sementes", "b2"),
    ("carota", "carote", "cenoura", "cenouras", "b1"),
    ("fagiolo", "fagioli", "feijão", "feijões", "b1"),
    ("pisello", "piselli", "ervilha", "ervilhas", "b2"),
    ("panino", "panini", "sanduíche", "sanduíches", "a2"),
    ("minuto", "minuti", "minuto", "minutos", "a1"),
    ("compleanno", "compleanni", "aniversário", "aniversários", "a2"),
    ("regalo", "regali", "presente", "presentes", "a2"),
    ("sogno", "sogni", "sonho", "sonhos", "a2"),
    ("nipote", "nipoti", "neto", "netos", "b1"),
    ("zia", "zie", "tia", "tias", "a2"),
    ("nonno", "nonni", "avô", "avôs", "a1"),
    ("nonna", "nonne", "avó", "avós", "a1"),
    ("vicino", "vicini", "vizinho", "vizinhos", "a2"),
    ("ospite", "ospiti", "convidado", "convidados", "b1"),
]

EXTRA_ADJ_PAIRS = [
    ("magro", "magri", "magro", "magros", "a2"),
    ("grasso", "grassi", "gordo", "gordos", "a2"),
    ("anziano", "anziani", "idoso", "idosos", "b1"),
    ("biondo", "biondi", "loiro", "loiros", "b1"),
    ("secco", "secchi", "seco", "secos", "b1"),
    ("bagnato", "bagnati", "molhado", "molhados", "b1"),
    ("fresco", "freschi", "fresco", "frescos", "a2"),
    ("maturo", "maturi", "maduro", "maduros", "b1"),
    ("crudo", "crudi", "cru", "crus", "b1"),
    ("cotto", "cotti", "cozido", "cozidos", "b1"),
    ("pigro", "pigri", "preguiçoso", "preguiçosos", "b1"),
    ("attivo", "attivi", "ativo", "ativos", "b1"),
    ("timido", "timidi", "tímido", "tímidos", "b1"),
    ("coraggioso", "coraggiosi", "corajoso", "corajosos", "b1"),
    ("onesto", "onesti", "honesto", "honestos", "b1"),
    ("moderno", "moderni", "moderno", "modernos", "b1"),
    ("antico", "antichi", "antigo", "antigos", "b1"),
    ("straniero", "stranieri", "estrangeiro", "estrangeiros", "b1"),
    ("pronto", "pronti", "pronto", "prontos", "a2"),
    ("famoso", "famosi", "famoso", "famosos", "b1"),
    ("povero", "poveri", "pobre", "pobres", "a2"),
    ("allegro", "allegri", "alegre", "alegres", "a2"),
    ("serio", "seri", "sério", "sérios", "b1"),
    ("severo", "severi", "severo", "severos", "b2"),
    ("dolce", "dolci", "carinhoso", "carinhosos", "b1"),
]

EXTRA_SINGLES = [
    # verbos
    ("dire", "dizer", "a1", ["falar"]),
    ("raccogliere", "recolher", "b2", ["colher", "juntar"]),
    ("offrire", "oferecer", "b1"),
    ("soffrire", "sofrer", "b1"),
    ("coprire", "cobrir", "b1"),
    ("aggiungere", "adicionar", "b2", ["acrescentar"]),
    ("togliere", "tirar", "b1", ["remover"]),
    ("riconoscere", "reconhecer", "b2"),
    ("preparare", "preparar", "a2"),
    ("presentare", "apresentar", "b1"),
    ("invitare", "convidar", "a2"),
    ("accompagnare", "acompanhar", "b1"),
    ("controllare", "controlar", "b1", ["verificar"]),
    ("misurare", "medir", "b1"),
    ("pesare", "pesar", "b1"),
    ("contare", "contar", "a2"),
    ("calcolare", "calcular", "b1"),
    ("disegnare", "desenhar", "a2"),
    ("scherzare", "brincar", "b1"),
    ("litigare", "brigar", "b1", ["discutir"]),
    ("alzare", "levantar", "b1"),
    ("abbassare", "abaixar", "b1"),
    ("chiarire", "esclarecer", "b2"),
    ("sporcare", "sujar", "b1"),
    ("bagnare", "molhar", "b1"),
    ("bruciare", "queimar", "b1"),
    ("bollire", "ferver", "b1"),
    ("friggere", "fritar", "b1"),
    ("mescolare", "misturar", "b1"),
    ("versare", "derramar", "b2", ["verter"]),
    ("assaggiare", "provar", "b1", ["experimentar"]),
    ("masticare", "mastigar", "b2"),
    ("respirare", "respirar", "b1"),
    ("soffiare", "soprar", "b2"),
    ("tossire", "tossir", "b2"),
    ("sognare", "sonhar", "a2"),
    ("divertirsi", "divertir-se", "a2", ["se divertir"]),
    ("annoiarsi", "entediar-se", "b1", ["se entediar"]),
    ("arrabbiarsi", "ficar bravo", "b1", ["irritar-se"]),
    ("sbrigarsi", "apressar-se", "b2", ["se apressar"]),
    ("vergognarsi", "ter vergonha", "b2", ["envergonhar-se"]),
    # substantivos (incontáveis / abstratos)
    ("clima", "clima", "b1"),
    ("temperatura", "temperatura", "b1"),
    ("ghiaccio", "gelo", "b1"),
    ("nebbia", "neblina", "b2", ["névoa"]),
    ("tuono", "trovão", "b2"),
    ("fulmine", "raio", "b2"),
    ("arcobaleno", "arco-íris", "b2"),
    ("ombra", "sombra", "b1"),
    ("alba", "amanhecer", "b2", ["alvorada"]),
    ("tramonto", "pôr do sol", "b2"),
    ("cielo", "céu", "a2"),
    ("terra", "terra", "a2"),
    ("aria", "ar", "a2"),
    ("ferro", "ferro", "b1"),
    ("oro", "ouro", "b1"),
    ("argento", "prata", "b1"),
    ("legno", "madeira", "b1"),
    ("vetro", "vidro", "b1"),
    ("plastica", "plástico", "b1"),
    ("cotone", "algodão", "b2"),
    ("lana", "lã", "b2"),
    ("denaro", "dinheiro", "b1"),
    ("ricchezza", "riqueza", "b2"),
    ("povertà", "pobreza", "b2"),
    ("confine", "fronteira", "b2"),
    ("bandiera", "bandeira", "b1"),
    ("esercito", "exército", "b2"),
    ("arma", "arma", "b1"),
    ("vittoria", "vitória", "b1"),
    ("sconfitta", "derrota", "b2"),
    ("pericolo", "perigo", "b1"),
    ("sicurezza", "segurança", "b1"),
    ("rischio", "risco", "b2"),
    ("fortuna", "sorte", "a2"),
    ("sfortuna", "azar", "b1"),
    ("destino", "destino", "b1"),
    ("emozione", "emoção", "b1"),
    ("sentimento", "sentimento", "b1"),
    ("carattere", "caráter", "b2"),
    ("bellezza", "beleza", "b1"),
    ("gioventù", "juventude", "b2"),
    ("infanzia", "infância", "b1"),
    ("nascita", "nascimento", "b1"),
    ("matrimonio", "casamento", "b1"),
    ("famiglia", "família", "a1"),
    ("genitori", "pais", "a1"),
    ("economia", "economia", "b2"),
    ("politica", "política", "b2"),
    ("religione", "religião", "b2"),
    ("filosofia", "filosofia", "c1"),
    ("ricerca", "pesquisa", "b2", ["busca"]),
    ("scoperta", "descoberta", "b2"),
    ("invenzione", "invenção", "b2"),
    ("matematica", "matemática", "b1"),
    ("geografia", "geografia", "b1"),
    ("biologia", "biologia", "b2"),
    ("chimica", "química", "b2"),
    ("fisica", "física", "b2"),
    ("documento", "documento", "b1"),
    ("video", "vídeo", "a2"),
    # ordinais / quantidade
    ("primo", "primeiro", "a1"),
    ("secondo", "segundo", "a1"),
    ("terzo", "terceiro", "a1"),
    ("ultimo", "último", "a1"),
    ("mezzo", "meio", "a2"),
    ("doppio", "dobro", "b1"),
    ("paio", "par", "b1"),
    ("metà", "metade", "a2"),
    ("dozzina", "dúzia", "b1"),
    # quantificadores / conectores avançados
    ("ciascuno", "cada um", "b2"),
    ("parecchio", "vários", "b2", ["bastante"]),
    ("qualsiasi", "qualquer", "b2"),
    ("chiunque", "qualquer um", "c1"),
    ("ovunque", "onde quer que", "c1", ["em qualquer lugar"]),
    ("dovunque", "em qualquer lugar", "c1"),
    ("eppure", "e no entanto", "c1", ["contudo"]),
    ("ossia", "ou seja", "c1", ["isto é"]),
    ("nonché", "bem como", "c1", ["assim como"]),
    ("malgrado", "apesar de", "c1", ["não obstante"]),
    # extras finais (verbos e sentidos)
    ("indossare", "vestir", "b1", ["usar"]),
    ("proteggere", "proteger", "b1"),
    ("attaccare", "atacar", "b1"),
    ("combattere", "combater", "b2"),
    ("conquistare", "conquistar", "b2"),
    ("esplorare", "explorar", "b2"),
    ("perdonare", "perdoar", "b1"),
    ("tradire", "trair", "b2"),
    ("ingannare", "enganar", "b2"),
    ("obbedire", "obedecer", "b2"),
    ("comandare", "comandar", "b2"),
    ("menzogna", "mentira", "b2"),
    ("sapore", "sabor", "b1"),
    ("odore", "cheiro", "b1", ["odor"]),
    ("profumo", "perfume", "b1"),
    ("gusto", "gosto", "b1", ["sabor"]),
    ("vista", "visão", "b1"),
    ("udito", "audição", "b2"),
    ("olfatto", "olfato", "b2"),
    ("tatto", "tato", "b2"),
]



def dart_list(items):
    return "[" + ", ".join("'" + s.replace("'", "\\'") + "'" for s in items) + "]"


def card(it, pt, level, pt_alt=None, hint=None):
    assert level in LEVELS, level
    fields = [
        "moduleId: 'essenciais'",
        f"level: CefrLevel.{level}",
        f"it: '{it}'",
        f"pt: '{pt}'",
    ]
    if pt_alt:
        fields.append(f"ptAlt: {dart_list(pt_alt)}")
    if hint:
        fields.append(f"hint: '{hint}'")
    return "  Flashcard(" + ", ".join(fields) + "),"


def main():
    lines = [
        "import '../models/flashcard.dart';",
        "",
        "/// Vocabulário italiano ESSENCIAL para fluência (módulo 'essenciais'):",
        "/// adjetivos, substantivos no singular e no plural, verbos, advérbios,",
        "/// pronomes e conectores. GERADO por tools/gen_essentials.py — não edite",
        "/// à mão; rode o script e substitua o arquivo.",
        "const List<Flashcard> kCardsEssenciais = [",
    ]

    seen = set()
    total = 0

    def add(it, pt, level, pt_alt=None, hint=None):
        nonlocal total
        if it in seen:
            return
        seen.add(it)
        lines.append(card(it, pt, level, pt_alt, hint))
        total += 1

    # substantivos singular + plural
    for it_s, it_p, pt_s, pt_p, lvl in NOUN_PAIRS + EXTRA_NOUN_PAIRS:
        add(it_s, pt_s, lvl, hint="substantivo (sing.)")
        add(it_p, pt_p, lvl, hint="substantivo (plural)")

    # adjetivos singular + plural
    for it_s, it_p, pt_s, pt_p, lvl in ADJ_PAIRS + EXTRA_ADJ_PAIRS:
        add(it_s, pt_s, lvl, hint="adjetivo (sing.)")
        add(it_p, pt_p, lvl, hint="adjetivo (plural)")

    # palavras avulsas
    for entry in SINGLES + EXTRA_SINGLES:
        if len(entry) == 4:
            it, pt, lvl, alts = entry
        else:
            it, pt, lvl = entry
            alts = None
        add(it, pt, lvl, alts)

    lines.append("];")
    lines.append("")

    out = "/home/user/italian-brazilian-flashcards/lib/data/cards_essenciais.dart"
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Gerados {total} cartões essenciais (únicos) em {out}")


if __name__ == "__main__":
    main()
